// export const cardList = [
//   {
//     id: 1,
//     theme: "Web Design",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "_orange",
//   },
//   {
//     id: 2,
//     theme: "Research",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "_green",
//   },
//   {
//     id: 3,
//     theme: "Web Design",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "_orange",
//   },
//   {
//     id: 4,
//     theme: "Copywriting",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "_purple",
//   },
//   {
//     id: 5,
//     theme: "Research",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "_green",
//   },
//   {
//     id: 6,
//     theme: "Research",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Нужно сделать",
//     color: "_green",
//   },
//   {
//     id: 7,
//     theme: "Research",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "В работе",
//     color: "_green",
//   },
//   {
//     id: 8,
//     theme: "Copywriting",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "В работе",
//     color: "_purple",
//   },
//   {
//     id: 9,
//     theme: "Web Design",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "В работе",
//     color: "_orange",
//   },
//   {
//     id: 10,
//     theme: "Research",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Тестирование",
//     color: "_green",
//   },
//   {
//     id: 11,
//     theme: "Research",
//     title: "Название задачи",
//     date: "30.10.23",
//     status: "Готово",
//     color: "_green",
//   },
// ];

export const statusList = [
  "Без статуса",
  "Нужно сделать",
  "В работе",
  "Тестирование",
  "Готово",
];
